# This file was generated by GoReleaser. DO NOT EDIT.
cask "mvn-llm" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/w8mr/mvn-llm/releases/download/v#{version}/mvn-llm_#{version}_darwin_amd64.tar.gz"
      sha256 "d10d803627931cf093070ae499810e0816fd5734b8198b0baed71cd8c8ca1775"
    end
    on_arm do
      url "https://github.com/w8mr/mvn-llm/releases/download/v#{version}/mvn-llm_#{version}_darwin_arm64.tar.gz"
      sha256 "a0be1fff7aa31fbcb5cd4a473ee4fc4c65196821bc1cec32b6ce358387b1c5e4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/w8mr/mvn-llm/releases/download/v#{version}/mvn-llm_#{version}_linux_amd64.tar.gz"
      sha256 "b0f20a969f41dbb2cfd5e91c1269235a4d8bcd222d690301d3e6315bd0e9c2c0"
    end
    on_arm do
      url "https://github.com/w8mr/mvn-llm/releases/download/v#{version}/mvn-llm_#{version}_linux_arm64.tar.gz"
      sha256 "214f3dea821696a635c43a866e4d15efbf194810233ea551ccb1f36e2a5a3120"
    end
  end

  name "mvn-llm"
  desc "A robust Maven build CLI for LLMs and developers"
  homepage "https://github.com/w8mr/maven-tool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mvn-llm"

  # No zap stanza required

  caveats <<~EOS
    Run 'mvn-llm --help' to get started.
  EOS
end
