# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MvnLlm < Formula
  desc "A robust Maven build CLI for LLMs and developers"
  homepage "https://github.com/w8mr/maven-tool"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/w8mr/mvn-llm/releases/download/v0.0.1/mvn-llm_0.0.1_darwin_amd64.tar.gz"
      sha256 "617e4d3e99bcecee47dc7cb72cefe389773c75d5a88a78dd159f3639d31a73bd"

      define_method(:install) do
        bin.install "mvn-llm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/w8mr/mvn-llm/releases/download/v0.0.1/mvn-llm_0.0.1_darwin_arm64.tar.gz"
      sha256 "4bd2094c7bb8c9668e65519ff990e550493b050b6a65209629b8e5bc6e9a0e07"

      define_method(:install) do
        bin.install "mvn-llm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/w8mr/mvn-llm/releases/download/v0.0.1/mvn-llm_0.0.1_linux_amd64.tar.gz"
      sha256 "6b82f7874d3346a0bcd8c00611314b046b411cd0aaaa372c7fc1d57cfa763dbe"
      define_method(:install) do
        bin.install "mvn-llm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/w8mr/mvn-llm/releases/download/v0.0.1/mvn-llm_0.0.1_linux_arm64.tar.gz"
      sha256 "912296c403bd21ce69b421406e3f97c58de97c64a1df650e410875e2be51a8d3"
      define_method(:install) do
        bin.install "mvn-llm"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'mvn-llm --help' to get started.
    EOS
  end
end
